### ISSUE TITLE
Pathname breaks Minimagick::Image::Info#cheap_info

### ISSUE THREAD

**Issue by scarfacedeb** [minimagick/minimagick#370]
MiniMagik prior to `v4.3.4` accepted Pathname, instead of a string, as image path for `MiniMagick::Image.new(path)`. And it was working as expected.

But after the upgrade from 4.3.2 to 4.5.1, I've noticed that we're getting the error when using `MiniMagick::Image#[]` because of `String#=~` in `Minimagick::Image::Info#cheap_info`

```
> MiniMagick::Image.new("img.jpg")["format"]
"JPEG"

> MiniMagick::Image.new(Pathname.new("img.jpg"))["format"]
NoMethodError: undefined method `=~' for #<Pathname:0x007ff1863a0f28>
from /*/vendor/bundle/ruby/2.3.0/gems/mini_magick-4.5.1/lib/mini_magick/image/info.rb:137:in `identify'
```

I've added necessary `to_s` calls to pathnames, but do you consider making it work with Pathname again?

Or is it unsupported feature?

Related commit: https://github.com/minimagick/minimagick/commit/cee2d8a64cb2c29e83e1c996794fe9434ab1eb03

**Comment by janko-m** [comment]
@scarfacedeb Yes, while previously it was only accidentally supported, I agree with supporting Pathname in `MiniMagick::Image.new` (since `MiniMagick::Image.open` already supports it as well). I will work on a fix shortly.
